### ISSUE TITLE
/cl command is not stable. Please check it!

### ISSUE THREAD

**Issue by madtomic** [dyukusi/Bukkit_plugins#6]
Null Error-

[23:59:16 INFO]: soandso issued server command: /cl

org.bukkit.command.CommandException: Unhandled exception executing command 'cl'
in plugin CraftLevel v0.0.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spi
got1543.jar:git-Spigot-1543]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:18
1) ~[spigot1543.jar:git-Spigot-1543]
        at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchCommand(CraftServe
r.java:767) ~[spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.PlayerConnection.handleCommand(PlayerCon
nection.java:1015) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java
:845) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.PacketPlayInChat.a(PacketPlayInChat.java
:28) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.PacketPlayInChat.handle(PacketPlayInChat
.java:65) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:184
) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java
:81) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:7
31) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:2
84) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:5
84) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java
:490) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:6
28) [spigot1543.jar:git-Spigot-1543]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at jp.mydns.dyukusi.craftlevel.command.BasicCommands.onCommand(BasicComm
ands.java:30) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spi
got1543.jar:git-Spigot-1543]
        ... 13 more

**Comment by madtomic** [comment]
Error commands such at no player not found isn't working too. Can you please check them all.

**Comment by dyukusi** [comment]
Thank you for the report.
I'll check it.

**Comment by dyukusi** [comment]
Fixed
